### ISSUE TITLE
关于运行过程中出现utf-8编码问题，造成seg_result.txt无法输出

### ISSUE THREAD

**Issue by thatLuckyCat** [jiangpinglei/Bert_ChinesewordSegment#1]
首先很感谢作者的分享，我尝试在自己的电脑上运行该代码，由于自己的失误，未看清机器配置要求，所以跑的时间很长，而且会出现编码问题，后来换在了Linux系统上运行（GeForce GTX 1080 Ti 10.92GB），并且将train.txt和test.txt都复制粘贴在新的utf-8编码下的文档中，然后运行没有编码问题，但是会出现assert len(token) != des_label[-1][1]报错AssertError，于是将该语句注释了，运行成功。

**Comment by jiangpinglei** [comment]
@thatLuckyCat 感谢指出，len(token) != des_label[-1][1]是一个bug，已解决

**Comment by thatLuckyCat** [comment]
不客气~




------------------ 原始邮件 ------------------
发件人: "Ray"<notifications@github.com>;
发送时间: 2019年5月28日(星期二) 下午3:45
收件人: "jiangpinglei/BERT_ChineseWordSegment"<BERT_ChineseWordSegment@noreply.github.com>;
抄送: "HEI  我在呢"<761913692@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [jiangpinglei/BERT_ChineseWordSegment] 关于运行过程中出现utf-8编码问题，造成seg_result.txt无法输出 (#1)




@thatLuckyCat 感谢指出，len(token) != des_label[-1][1]是一个bug，已解决
