### ISSUE TITLE
    assert len(token) != des_label[-1][1] failed

### ISSUE THREAD

**Issue by SeekPoint** [jiangpinglei/Bert_ChinesewordSegment#3]
INFO:tensorflow:Processing example: 9000
INFO:tensorflow:prediction_loop marked as finished
INFO:tensorflow:prediction_loop marked as finished
INFO:tensorflow:***** Eval results *****
INFO:tensorflow:  count = 9925
INFO:tensorflow:  precision_avg = 0.9798230846013376
INFO:tensorflow:  recall_avg = 0.978754065670963
INFO:tensorflow:  f1_avg = 0.9789455253068698
INFO:tensorflow:  error_avg = 0.021007439371308115
Traceback (most recent call last):
  File "run_cut.py", line 662, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run_cut.py", line 653, in main
    output_seg_result(FLAGS.output_dir, ori_labels, des_labels)
  File "run_cut.py", line 254, in output_seg_result
    assert len(token) != des_label[-1][1]
AssertionError
ub16c9@ub16c9-gpu:/media/ub16c9/3T1_blue/ub16_prj/_BERT_/BERT_ChineseWordSegment$

**Comment by kangzhonghua** [comment]
我也遇到这个问题

**Comment by jiangpinglei** [comment]
不好意思，这里是一个bug把这行注释掉就可以了
