### ISSUE TITLE
How can I use the trained result to predict a single sentence?

### ISSUE THREAD

**Issue by temco** [jiangpinglei/Bert_ChinesewordSegment#5]
Is there such a predict_single.py provided then? I'm not so familiar with BERT, ^_^

**Comment by jiangpinglei** [comment]
> Is there such a predict_single.py provided then? I'm not so familiar with BERT, ^_^

Not yet. Maybe I will add it  when I am totally free. For now you may use the batch prediction just set batch_size=1.

**Comment by temco** [comment]
OK, thank you

Ray <notifications@github.com> 于2019年7月16日周二 下午7:11写道：
